{"name": "test_failing", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1, 2, 3) == (3, 2, 1)", "trace": "def test_failing():\n>       assert (1, 2, 3) == (3, 2, 1)\nE       assert (1, 2, 3) == (3, 2, 1)\n\ntest22.py:8: AssertionError"}, "start": 1634105254574, "stop": 1634105254575, "uuid": "705437a5-0541-4d5c-8510-66cdf8de6d8c", "historyId": "1a3fc1b709eeb683c10c42d9e0f662b1", "testCaseId": "712d2cdcc3e5686931580e6f0490e61b", "fullName": "case.test22#test_failing", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test22"}, {"name": "host", "value": "LAPTOP-9964GMTD"}, {"name": "thread", "value": "17896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test22"}]}