{"uuid": "ccc0958e-e103-47bd-a691-567adf9bc29b", "children": ["47b0e72f-6a59-4cbc-b37a-1535447d6680"], "befores": [{"name": "ls_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'Login' object has no attribute 'login'\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation\\case\\conftest.py\", line 48, in ls_login\n    login_ls(lisi_info,'lisi_token')\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation\\common\\logintoken.py\", line 63, in login_ls\n    return Login(admin_info,ls_token)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation\\common\\logintoken.py\", line 25, in __init__\n    result = self.login(username=self.username, password=self.password)\n"}, "start": 1637212637794, "stop": 1637212637794}], "start": 1637212637794, "stop": 1637212637854}