{"name": "test_admin_login[用户名错误的登录]", "status": "broken", "statusDetails": {"message": "NameError: name 'b' is not defined", "trace": "self = <case.test_member_controller.test_login.Test_DengLu object at 0x000001A25D7FB0F0>\ndata0 = {'password': '123456', 'username': 'sss'}\nexpect = {'except_code': 500, 'except_msg': 'Bad credentials', 'info': '用户名错误的登录'}\nzs_login = <common.logintoken.Login object at 0x000001A25D85B828>\nls_login = <common.logintoken.Login object at 0x000001A25DA2B978>\nmember_controller_z = <api.admin.member_controller_api.MemberControllerApi object at 0x000001A25DA2BCC0>\n\n    @pytest.mark.parametrize(\"data0,expect\", data,ids=[data[i][1]['info'] for i in range(len(data))])  # 参数化测试用例\n    @decorate_log\n    def test_admin_login(self,data0,expect,zs_login,ls_login,member_controller_z):\n        print(\"data_0\", data0,expect)\n        \"\"\"请求登录测试用例\"\"\"\n        actual_data = member_controller_z.login(password=data0['password']\n                       ,username=data0['username'])\n        \"\"\"断言\"\"\"\n>       assert_api(actual_data,expect)\n\ntest_login.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\common\\logger.py:67: in log\n    raise e\n..\\..\\common\\logger.py:63: in log\n    func(*args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual_data = {'code': 500, 'data': None, 'message': 'Bad credentials'}\nexpect_data = {'except_code': 500, 'except_msg': 'Bad credentials', 'info': '用户名错误的登录'}\n\n    @decorate_log\n    def assert_api(actual_data,expect_data):\n        # Logger.info(\"*************** {}开始执行用例 ***************\".format(expect_data['info']))\n        try:\n            # assert actual_data['code'] == expect_data['except_code']\n            # assert actual_data['message'] == expect_data['except_msg']\n            # 用set来实现\n            aa = set(expect_data.items())  # {('a', 1), ('b', 2)}\n            bb = set(actual_data.items())  # {('a', 1), ('c', 3), ('b', 2)}\n            #\n>           print(aa.issubset(b.items()))  ## true\nE           NameError: name 'b' is not defined\n\n..\\..\\common\\assert_api.py:28: NameError"}, "steps": [{"name": "响应日志", "status": "passed", "parameters": [{"name": "status_code", "value": "200"}, {"name": "text", "value": "{'code': 500, 'message': 'Bad credentials', 'data': None}"}], "start": 1634622972880, "stop": 1634622972880}, {"name": "请求日志", "status": "passed", "parameters": [{"name": "url", "value": "'http://121.37.169.128:8201/mall-member/sso/login?platform=test&time=1634622972620&password=123456&username=sss'"}, {"name": "method", "value": "'post'"}, {"name": "body", "value": "{}"}, {"name": "headers", "value": "{'Content-Type': 'application/json'}"}], "start": 1634622972880, "stop": 1634622972880}], "attachments": [{"name": "log", "source": "4a98133e-f101-41f1-b423-84e34a52c76e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data0", "value": "{'username': 'sss', 'password': '123456'}"}, {"name": "expect", "value": "{'except_msg': 'Bad credentials', 'except_code': 500, 'info': '用户名错误的登录'}"}], "start": 1634622972620, "stop": 1634622972881, "uuid": "eedf851d-8746-4d2d-9923-8aa095fecb36", "historyId": "a42004a83c86384abc1089e2e61541c7", "testCaseId": "02c7f242c9f09fbdefa4b8f5b820915e", "fullName": "case.test_member_controller.test_login.Test_DengLu#test_admin_login", "labels": [{"name": "feature", "value": "测试member_controller模块"}, {"name": "story", "value": "登录功能"}, {"name": "parentSuite", "value": "case.test_member_controller"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_DengLu"}, {"name": "host", "value": "LAPTOP-9964GMTD"}, {"name": "thread", "value": "20740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_member_controller.test_login"}]}