{"name": "test_admin_login[case3_用户名密码错误的登录]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <case.test_member_controller.test_login.Test_DengLu object at 0x00000265FF52A668>\ncase_data = {'body': {'password': '9999997', 'username': 'adminhhhhhhhhhh'}, 'case_name': 'case3_用户名密码错误的登录', 'expect': {'code': 500, 'message': 'Bad credentials'}}\nmember_controller_z = <api.admin.member_controller_api.MemberControllerApi object at 0x00000265FF3F3940>\n\n    @decorate_log\n    @pytest.mark.parametrize(\"case_data\", data,ids=[data[i]['case_name'] for i in range(len(data))])  # 参数化测试用例\n    def test_admin_login(self,case_data,member_controller_z):\n        # time.sleep(10)\n        print(\"case_data\",case_data)\n        case_body = case_data['body']\n        \"\"\"请求登录测试用例\"\"\"\n        with allure.step('登录步骤'):\n            actual_data = member_controller_z.login(password=case_body['password']\n                           ,username=case_body['username'])\n            \"\"\"断言\"\"\"\n            print(\"账号密码\",case_body['username'],case_body['password'])\n            print(\"566666:\",actual_data)\n>           assert_api(actual_data,case_data['expect'])\n\ntest_login.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\common\\logger.py:68: in log\n    raise e\n..\\..\\common\\logger.py:64: in log\n    func(*args, **kwargs)\n..\\..\\common\\assert_api.py:36: in assert_api\n    raise e\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual_data = {'code': 200, 'data': {'expiresIn': 86399, 'refreshToken': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZ...mv4YDDRxlgjTKtWsHir6eW8-V5sYo28qydxTqbNCR74x46QbxkEZR9qYjiCyky4DoL1Y_WaOE', 'tokenHead': 'Bearer '}, 'message': '操作成功'}\nexpect_data = {'code': 500, 'message': 'Bad credentials'}\n\n    @decorate_log\n    def assert_api(actual_data,expect_data):\n        # Logger.info(\"*************** {}开始执行用例 ***************\".format(expect_data['info']))\n        Logger.info(\"\\r\\nassert:\\r\\n 实际结果：{}，\\r\\n期望结果{}\".format(actual_data, expect_data))\n        try:\n            a = expect_data\n            b = actual_data\n            for i, j in a.items():\n                if i in b.keys():\n>                   assert j == b[i]\nE                   AssertionError\n\n..\\..\\common\\assert_api.py:27: AssertionError"}, "steps": [{"name": "登录步骤", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\case\\test_member_controller\\test_login.py\", line 38, in test_admin_login\n    assert_api(actual_data,case_data['expect'])\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logger.py\", line 68, in log\n    raise e\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logger.py\", line 64, in log\n    func(*args, **kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\assert_api.py\", line 36, in assert_api\n    raise e\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\assert_api.py\", line 27, in assert_api\n    assert j == b[i]\n"}, "steps": [{"name": "响应日志", "status": "passed", "parameters": [{"name": "status_code", "value": "200"}, {"name": "text", "value": "{'code': 200, 'message': '操作成功', 'data': {'token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImFsbCJdLCJpZCI6MjQzNDQyNywiZXhwIjoxNjQ4MjU1NTY1LCJhdXRob3JpdGllcyI6WyLliY3lj7DkvJrlkZgiXSwianRpIjoiMjU5MzA1NWEtZTY2My00MjhiLTgwMmYtZmQ0ZThiNjQ1YmZkIiwiY2xpZW50X2lkIjoicG9ydGFsLWFwcCJ9.Td_Lm6MOWEA69Fl9CE69cx_ZIEHMO22Wjc0CqKGuz6RJ45_8B55nhuEcfgMWmlhOqnEIz8oIkqi-R_9jY6M-cM1n2G7yPYaFOAmv4YDDRxlgjTKtWsHir6eW8-V5sYo28qydxTqbNCR74x46QbxkEZR9qYjiCyky4DoL1Y_WaOE', 'refreshToken': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImFsbCJdLCJhdGkiOiIyNTkzMDU1YS1lNjYzLTQyOGItODAyZi1mZDRlOGI2NDViZmQiLCJpZCI6MjQzNDQyNywiZXhwIjoxNjQ4NzczOTY1LCJhdXRob3JpdGllcyI6WyLliY3lj7DkvJrlkZgiXSwianRpIjoiMWI3MWExYTAtYWYwYS00NGFiLWJlY2UtMzRhZDlmMTYwZWM5IiwiY2xpZW50X2lkIjoicG9ydGFsLWFwcCJ9.D30-cbcgylSUuf8ZM7pspm0dW3S1aC-PT-EDIaHxz1RIh0VtNRahOARygOWLVneA5M-WHSjJFRAyvgj9y4BnaCZg_G_Q74jujxU6hDh4NUiJDSgvp-hWRE3mPAH-fcnl6vpGdUFFwt6j1zocHIbrSGe0FVshzFKko3Ah_tPQg9w', 'tokenHead': 'Bearer ', 'expiresIn': 86399}}"}], "start": 1648169164288, "stop": 1648169164288}, {"name": "请求日志", "status": "passed", "parameters": [{"name": "url", "value": "'http://121.37.169.128:8201/mall-member/sso/login?platform=test&time=1648169163923&username=admin&password=123456'"}, {"name": "method", "value": "'post'"}, {"name": "body", "value": "{}"}, {"name": "headers", "value": "{'Content-Type': 'application/json'}"}], "start": 1648169164288, "stop": 1648169164288}], "start": 1648169163923, "stop": 1648169164289}], "attachments": [{"name": "log", "source": "654eaf04-bd89-4823-b21f-2f2f6903a0e1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case_data", "value": "{'case_name': 'case3_用户名密码错误的登录', 'body': {'username': 'adminhhhhhhhhhh', 'password': '9999997'}, 'expect': {'message': 'Bad credentials', 'code': 500}}"}], "start": 1648169163923, "stop": 1648169164290, "uuid": "1dc8f0a9-5a41-4f54-8dbb-606dd7acd3db", "historyId": "e8e60fbd9f64690605ffb6f55812c06c", "testCaseId": "02c7f242c9f09fbdefa4b8f5b820915e", "fullName": "case.test_member_controller.test_login.Test_DengLu#test_admin_login", "labels": [{"name": "feature", "value": "测试member_controller模块"}, {"name": "story", "value": "登录功能"}, {"name": "parentSuite", "value": "case.test_member_controller"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_DengLu"}, {"name": "host", "value": "LAPTOP-9964GMTD"}, {"name": "thread", "value": "58824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_member_controller.test_login"}]}